version: '3.9'

services:
  token-service:
    build: ../SRMAuth
    ports:
      - "5000:8080"
    depends_on:
      - redis
    networks:
      - srm-network

  core-service:
    build: ../SRMCore
    ports:
      - "5001:8080"
    depends_on:
      - redis
      - token-service
      - db
    networks:
      - srm-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - srm-network

  db:  # <-- richtig eingerückt!
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: srm-db
    environment:
      SA_PASSWORD: "SuperSicher123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - srm-network

networks:
  srm-network:
    driver: bridge
