version: '3.9'

networks:
  redmine_net:
  redmineDB_net:
  srm-network:

services:

  redmine:
    image: redmine
    restart: always
    networks:
      - redmine_net
      - redmineDB_net
      - srm-network
    environment:
      REDMINE_DB_MYSQL: redmine-db
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: Securepwd123!
    depends_on:
      - redmine-db
    ports:
      - "3000:3000"
    command: >
      bash -c "
      echo '⏳ Waiting for Redmine to initialize...';
      sleep 30;
      /docker-entrypoint.sh rails server -b 0.0.0.0;
      "


  redmine-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: Securepwd123!
    networks:
      - redmineDB_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-predmine"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - redmine
    ports:
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./nginx:/etc/nginx/conf.d:ro
    networks:
      - redmine_net

  token-service:
    build: ../SRMAuth
    ports:
      - "5000:8080"
    depends_on:
      - redis
    networks:
      - srm-network

  core-service:
    build: ../SRMCore
    ports:
      - "5001:8080"
    depends_on:
      - redis
      - token-service
      - srm-db
    networks:
      - srm-network
      - redmine_net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - srm-network

  srm-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: srm-db
    environment:
      SA_PASSWORD: "SuperSicher123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - srm-network
